
server:
  port: 82
  servlet:
    context-path: /
logging:
  level:
    cn.rui: debug
spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  redis:
    host: localhost
    database: 1
    port: 6379
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000

dubbo:
  application:
    name: boot-health-backend
  registry:
    address: zookeeper://127.0.0.1:2181

